# runtime version
iHubRuntimeVersion=2.0

#scale to zero properties
ihub.releaseconfig.scaleToZeroEnabled=false
#error handling properties
ihub.ueh.eventpublisher.redelivery-policy-enabled=true
ihub.ueh.eventpublisher.redeliveryPolicy.maximum-redeliveries=4
ihub.ueh.eventpublisher.redeliveryPolicy.redelivery-delay=3000
ihub.ueh.eventpublisher.dead-letter-channel-enabled=true
ihub.ueh.event.default-values.error-type=TECHNICAL
ihub.ueh.event.default-values.severity=WARNING
ihub.ueh.event.default-values.replay.is-replayable=true
ihub.ueh.event.default-values.replay.automatic-replay=false
ihub.ueh.event.default-values.replay.maximum-replays=3 

#ok